services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    networks:
      opencms-network:
        ipv4_address: 192.168.0.2
    volumes:
      - postgres-data:/var/lib/postgresql/data

  opencms:
    image: opencms-tomcat
    container_name: opencms
    ports:
      - "8080:8080"
    networks:
      opencms-network:
        ipv4_address: 192.168.0.3
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=senha

  nginx:
    image: proxy-nginx
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - opencms
    networks:
      opencms-network:
        ipv4_address: 192.168.0.4

networks:
  opencms-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16

volumes:
  postgres-data: